services:
  - type: web
    name: resolva-jato
    runtime: node
    plan: free
    buildCommand: ''
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: '20'
