'use client';

import { ChangeEvent, forwardRef, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, BookOpen, Bot, Check, ChevronLeft, ChevronRight, Download, FileSearch, GraduationCap, Loader2, Plus, RefreshCw, Sparkles, Trash2, Upload, Wand2 } from 'lucide-react';
import { AuthGate } from '@/components/auth/auth-gate';
import { RemoveBrandingUpsell } from '@/components/billing/remove-branding-upsell';
import { DocumentExportShell } from '@/components/brand/document-export-shell';
import { ToolsWatermark } from '@/components/brand/tools-watermark';
import { ToolsBackButton } from '@/components/shared/tools-back-button';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select } from '@/components/ui/select';
import { useAuth } from '@/hooks/use-auth';
import { exportElementToPdf } from '@/lib/curriculo/pdf';
import { cn } from '@/lib/utils';
import { completion, createEntry, createLattesProfile, LATTES_STORAGE_KEY, validateProfile } from '@/lib/lattes/model';
import type { AcademicEntry, LattesProfile, LattesSectionId } from '@/lib/lattes/types';

const steps = [
  { id: 'geral', label: 'Identidade', hint: 'Dados gerais e resumo' },
  { id: 'formacao', label: 'Trajetória', hint: 'Formação e atuação' },
  { id: 'bibliografica', label: 'Produções', hint: 'Pesquisa e resultados' },
  { id: 'redes', label: 'Impacto', hint: 'Redes e indicadores' },
  { id: 'revisao', label: 'Revisão', hint: 'Validar e gerar' }
] as const;

const sections: { id: LattesSectionId; label: string; description: string }[] = [
  { id: 'formacao', label: 'Formação acadêmica', description: 'Graduação, especialização, mestrado, doutorado e pós-doutorado' },
  { id: 'atuacao', label: 'Atuação profissional', description: 'Vínculos, cargos, docência e pesquisa' },
  { id: 'pesquisa', label: 'Áreas e linhas de pesquisa', description: 'Áreas CNPq, subáreas, especialidades e palavras-chave' },
  { id: 'projetos', label: 'Projetos', description: 'Pesquisa, desenvolvimento, inovação e extensão' },
  { id: 'bibliografica', label: 'Produção bibliográfica', description: 'Artigos, livros, capítulos, trabalhos e resumos' },
  { id: 'tecnica', label: 'Produção técnica', description: 'Software, relatórios, consultorias, cursos e material didático' },
  { id: 'patentes', label: 'Patentes e registros', description: 'Depósitos, concessões e licenciamentos' },
  { id: 'eventos', label: 'Eventos', description: 'Participação, organização, palestras e mesas' },
  { id: 'orientacoes', label: 'Orientações', description: 'IC, TCC, mestrado, doutorado e pós-doutorado' },
  { id: 'bancas', label: 'Bancas', description: 'Qualificações, defesas e concursos' },
  { id: 'premios', label: 'Prêmios e títulos', description: 'Honrarias, menções e distinções' },
  { id: 'inovacao', label: 'Inovação', description: 'Produtos, startups, spin-offs e tecnologias' },
  { id: 'extensao', label: 'Extensão', description: 'Ações, projetos, cursos e eventos comunitários' },
  { id: 'idiomas', label: 'Idiomas', description: 'Compreensão, fala, leitura e escrita' }
];

const sample: LattesProfile = { ...createLattesProfile(), title: 'Currículo acadêmico — Marina Costa', general: { fullName: 'Marina Alves Costa', citationName: 'COSTA, M. A.', nationality: 'Brasileira', city: 'Belo Horizonte, MG', email: 'marina.costa@universidade.br', orcid: '0000-0002-1825-0097', summary: 'Doutora em Ciência da Computação, com atuação em inteligência artificial responsável, ciência de dados e políticas públicas digitais.' }, keywords: ['Inteligência artificial', 'Ciência de dados', 'Ética em tecnologia'], entries: [createEntry('formacao', { title: 'Doutorado em Ciência da Computação', institution: 'Universidade Federal de Minas Gerais', startYear: '2018', endYear: '2022', description: 'Tese sobre explicabilidade em sistemas de decisão automatizada.' }), createEntry('atuacao', { title: 'Professora Adjunta', institution: 'Universidade Federal de Minas Gerais', startYear: '2023', endYear: 'Atual', description: 'Docência, pesquisa e orientação no Departamento de Computação.' }), createEntry('bibliografica', { title: 'Responsible AI in public decision systems', institution: 'Journal of AI Research', startYear: '2024', identifier: '10.5555/example.2024.01', authors: 'Costa, M. A.; Silva, R. P.', description: 'Artigo completo publicado em periódico.' }), createEntry('projetos', { title: 'IA responsável para serviços públicos', institution: 'CNPq / UFMG', startYear: '2023', endYear: '2026', status: 'Em andamento', description: 'Projeto de pesquisa e desenvolvimento.' })], academicNetworks: [{ name: 'ORCID', url: 'https://orcid.org/0000-0002-1825-0097' }, { name: 'Google Scholar', url: 'https://scholar.google.com/' }], indicators: { articles: '18', citations: '342', hIndex: '9', i10: '8' } };

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }

export function LattesApp() {
  const { usage } = useAuth();
  const brandDocuments = !usage.unlimited;
  const previewRef = useRef<HTMLDivElement>(null); const fileRef = useRef<HTMLInputElement>(null);
  const [profile, setProfile] = useState<LattesProfile>(createLattesProfile); const [hydrated, setHydrated] = useState(false);
  const [saveState, setSaveState] = useState<'saved' | 'saving'>('saved'); const [assistant, setAssistant] = useState('');
  const [assistantStatus, setAssistantStatus] = useState(''); const [importValue, setImportValue] = useState('');
  const [importing, setImporting] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState('');
  const issues = useMemo(() => validateProfile(profile), [profile]); const score = useMemo(() => completion(profile), [profile]);
  const step = profile.currentStep; const active = steps[step];

  useEffect(() => { try { const raw = localStorage.getItem(LATTES_STORAGE_KEY); if (raw) setProfile({ ...createLattesProfile(), ...JSON.parse(raw) }); } catch {} setHydrated(true); }, []);
  useEffect(() => { if (!hydrated) return; setSaveState('saving'); const timer = setTimeout(() => { localStorage.setItem(LATTES_STORAGE_KEY, JSON.stringify({ ...profile, updatedAt: new Date().toISOString() })); setSaveState('saved'); }, 650); return () => clearTimeout(timer); }, [profile, hydrated]);
  const patch = (next: Partial<LattesProfile>) => setProfile((value) => ({ ...value, ...next }));
  const patchGeneral = (key: keyof LattesProfile['general'], value: string) => patch({ general: { ...profile.general, [key]: value } });
  const entriesFor = (id: LattesSectionId) => profile.entries.filter((entry) => entry.section === id);
  const updateEntry = (id: string, changes: Partial<AcademicEntry>) => patch({ entries: profile.entries.map((item) => item.id === id ? { ...item, ...changes } : item) });
  const removeEntry = (id: string) => patch({ entries: profile.entries.filter((item) => item.id !== id) });

  function runAssistantInterpret() {
    const text = assistant.trim(); if (!text) return; const year = text.match(/(?:19|20)\d{2}/)?.[0] || '';
    let section: LattesSectionId = /artigo|doi|public|livro|capítulo/i.test(text) ? 'bibliografica' : /professor|trabalh|cargo|vínculo/i.test(text) ? 'atuacao' : /projeto|pesquisa/i.test(text) ? 'projetos' : 'formacao';
    patch({ entries: [...profile.entries, createEntry(section, { title: text.replace(/^(eu |sou |publiquei |concluí |fiz )/i, '').slice(0, 110), startYear: year, description: 'Registro criado pelo assistente; revise os campos antes da exportação.' })] });
    setAssistant(''); setAssistantStatus(`Registro sugerido em “${sections.find((s) => s.id === section)?.label}”. Revise os dados.`); setTimeout(() => setAssistantStatus(''), 4000);
  }

  async function importAcademic() {
    const value = importValue.trim(); if (!value) return; setImporting(true); setError('');
    try {
      if (/^10\.\d{4,9}\//i.test(value)) { const response = await fetch(`https://api.crossref.org/works/${encodeURIComponent(value)}`); if (!response.ok) throw new Error(); const data = (await response.json()).message; patch({ entries: [...profile.entries, createEntry('bibliografica', { title: data.title?.[0] || 'Publicação importada', institution: data['container-title']?.[0] || '', startYear: String(data.published?.['date-parts']?.[0]?.[0] || ''), identifier: value, authors: (data.author || []).map((a: { family?: string; given?: string }) => `${a.family || ''}, ${a.given || ''}`).join('; '), description: 'Metadados obtidos via Crossref. Confirme antes de usar.' })] }); setImportValue(''); }
      else if (/^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$/i.test(value)) { patchGeneral('orcid', value); patch({ academicNetworks: [...profile.academicNetworks.filter((n) => n.name !== 'ORCID'), { name: 'ORCID', url: `https://orcid.org/${value}` }] }); setImportValue(''); }
      else throw new Error();
    } catch { setError('Não foi possível consultar agora. Verifique o DOI/ORCID ou preencha manualmente.'); } finally { setImporting(false); }
  }

  function handleUpload(event: ChangeEvent<HTMLInputElement>) { const files = Array.from(event.target.files || []); if (!files.length) return; setUploading(true); setTimeout(() => { patch({ entries: [...profile.entries, ...files.map((file) => createEntry(/artigo|paper/i.test(file.name) ? 'bibliografica' : 'formacao', { title: file.name.replace(/\.[^.]+$/, ''), description: `Documento “${file.name}” anexado para conferência. Extração assistida disponível quando o serviço de OCR for conectado.` }))] }); setUploading(false); if (fileRef.current) fileRef.current.value = ''; }, 800); }
  async function exportPdf() { if (!previewRef.current) return; setError(''); try { await exportElementToPdf(previewRef.current, `${(profile.general.fullName || 'curriculo-academico').replace(/\s+/g, '_')}.pdf`, { branded: brandDocuments }); } catch { setError('Não foi possível gerar o PDF. Tente novamente.'); } }

  if (!hydrated) return <div className="grid min-h-[420px] place-items-center"><Loader2 className="h-7 w-7 animate-spin text-teal-700" /></div>;
  return <AuthGate title="Currículo Lattes Inteligente" description="Crie sua conta gratuita para salvar e gerar seu currículo acadêmico.">
    <div className="space-y-5 pb-10">
      <RemoveBrandingUpsell />
      <section className="relative overflow-hidden rounded-[28px] border border-slate-200 bg-gradient-to-br from-white via-white to-teal-50 p-5 shadow-sm sm:p-7"><ToolsWatermark />
        <div className="relative flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div className="flex gap-4"><span className="grid h-13 w-13 shrink-0 place-items-center rounded-2xl bg-teal-700 text-white shadow-lg shadow-teal-900/10"><GraduationCap className="h-6 w-6" /></span><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold text-slate-950 sm:text-3xl">Lattes Inteligente</h1><span className="rounded-full bg-teal-100 px-2.5 py-1 text-[11px] font-bold uppercase tracking-wide text-teal-800">Acadêmico</span></div><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">Organize sua trajetória com rigor acadêmico, revisão inteligente e versões prontas para cada oportunidade.</p></div></div>
          <div className="flex flex-wrap items-center gap-2">
            <ToolsBackButton size="default" />
            <Button variant="outline" onClick={() => setProfile(sample)}><Sparkles className="h-4 w-4" />Ver exemplo</Button>
            <Button onClick={exportPdf}><Download className="h-4 w-4" />Gerar PDF premium</Button>
          </div></div>
        <div className="relative mt-6 grid gap-3 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="mb-2 flex justify-between text-xs font-semibold text-slate-600"><span>Completude do perfil</span><span>{score}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-gradient-to-r from-teal-600 to-cyan-500 transition-all" style={{ width: `${score}%` }} /></div></div><div className="flex items-center gap-2 text-xs font-medium text-slate-500">{saveState === 'saving' ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : <Check className="h-3.5 w-3.5 text-emerald-600" />}{saveState === 'saving' ? 'Salvando alterações' : 'Salvo automaticamente'}</div></div>
      </section>

      <section className="grid gap-2 rounded-[24px] border border-slate-200 bg-white p-3 shadow-sm md:grid-cols-5">{steps.map((item, index) => <button key={item.id} onClick={() => patch({ currentStep: index })} className={cn('flex items-center gap-3 rounded-2xl p-3 text-left transition', index === step ? 'bg-slate-950 text-white shadow-md' : index < step ? 'bg-teal-50 text-teal-900' : 'text-slate-500 hover:bg-slate-50')}><span className={cn('grid h-8 w-8 shrink-0 place-items-center rounded-full text-xs font-bold', index === step ? 'bg-teal-400 text-slate-950' : index < step ? 'bg-teal-600 text-white' : 'bg-slate-100')}>{index < step ? <Check className="h-4 w-4" /> : index + 1}</span><span><b className="block text-xs">{item.label}</b><small className="hidden text-[10px] opacity-70 lg:block">{item.hint}</small></span></button>)}</section>

      <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_350px]">
        <main className="space-y-5">
          <section className="rounded-[28px] border border-teal-200 bg-teal-950 p-5 text-white shadow-sm"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-teal-400 text-teal-950"><Bot className="h-5 w-5" /></span><div className="min-w-0 flex-1"><h2 className="font-bold">Conte sua trajetória</h2><p className="mt-0.5 text-xs leading-5 text-teal-100">Ex.: “Concluí mestrado em Educação na UFF em 2021” ou “Publiquei um artigo em 2024”.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input value={assistant} onChange={(e) => setAssistant(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && runAssistantInterpret()} placeholder="Escreva naturalmente…" className="border-white/20 bg-white/10 text-white placeholder:text-teal-200" /><Button onClick={runAssistantInterpret} className="bg-teal-400 text-teal-950 hover:bg-teal-300"><Wand2 className="h-4 w-4" />Interpretar</Button></div>{assistantStatus && <p className="mt-2 text-xs font-medium text-teal-200">{assistantStatus}</p>}</div></div></section>

          {active.id === 'geral' && <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5"><h2 className="text-xl font-bold text-slate-950">Identidade acadêmica</h2><p className="mt-1 text-sm text-slate-500">Use dados fiéis aos documentos e identificadores acadêmicos.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome completo *"><Input value={profile.general.fullName} onChange={(e) => patchGeneral('fullName', e.target.value)} placeholder="Nome civil completo" /></Field><Field label="Nome em citações"><Input value={profile.general.citationName} onChange={(e) => patchGeneral('citationName', e.target.value)} placeholder="SOBRENOME, N. N." /></Field><Field label="Nacionalidade"><Input value={profile.general.nationality} onChange={(e) => patchGeneral('nationality', e.target.value)} /></Field><Field label="Cidade / UF"><Input value={profile.general.city} onChange={(e) => patchGeneral('city', e.target.value)} placeholder="Cidade, UF" /></Field><Field label="E-mail acadêmico"><Input type="email" value={profile.general.email} onChange={(e) => patchGeneral('email', e.target.value)} /></Field><Field label="ORCID"><Input value={profile.general.orcid} onChange={(e) => patchGeneral('orcid', e.target.value)} placeholder="0000-0000-0000-0000" /></Field><div className="sm:col-span-2"><Field label="Resumo acadêmico"><Textarea rows={6} value={profile.general.summary} onChange={(e) => patchGeneral('summary', e.target.value)} placeholder="Síntese da formação, atuação, temas de pesquisa e contribuições…" /></Field></div><div className="sm:col-span-2"><Field label="Palavras-chave"><Input value={profile.keywords.join(', ')} onChange={(e) => patch({ keywords: e.target.value.split(',').map((v) => v.trim()).filter(Boolean) })} placeholder="Educação, Políticas públicas, Ciência de dados" /></Field></div></div></section>}

          {(active.id === 'formacao' || active.id === 'bibliografica') && <div className="space-y-4">{sections.filter((section) => active.id === 'formacao' ? ['formacao','atuacao','pesquisa','projetos'].includes(section.id) : !['formacao','atuacao','pesquisa','projetos','idiomas'].includes(section.id)).map((section) => <SectionEditor key={section.id} section={section} entries={entriesFor(section.id)} onAdd={() => patch({ entries: [...profile.entries, createEntry(section.id)] })} onUpdate={updateEntry} onRemove={removeEntry} />)}</div>}

          {active.id === 'redes' && <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-bold">Redes e impacto</h2><p className="mt-1 text-sm text-slate-500">Consolide identificadores e métricas, sempre informando a fonte e data de consulta.</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(['articles','citations','hIndex','i10'] as const).map((key) => <Field key={key} label={{articles:'Artigos',citations:'Citações',hIndex:'Índice h',i10:'Índice i10'}[key]}><Input inputMode="numeric" value={profile.indicators[key]} onChange={(e) => patch({ indicators: { ...profile.indicators, [key]: e.target.value } })} /></Field>)}</div><div className="mt-6"><Field label="Rede acadêmica"><div className="flex gap-2"><Input placeholder="Cole uma URL de ORCID, Scholar, Scopus…" onKeyDown={(e) => { if (e.key === 'Enter' && e.currentTarget.value) { patch({ academicNetworks: [...profile.academicNetworks, { name: 'Perfil acadêmico', url: e.currentTarget.value }] }); e.currentTarget.value=''; } }} /><Button variant="outline">Adicionar</Button></div></Field>{profile.academicNetworks.length ? <div className="mt-3 flex flex-wrap gap-2">{profile.academicNetworks.map((network, index) => <span key={`${network.url}-${index}`} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700">{network.name}</span>)}</div> : <p className="mt-3 text-sm text-slate-400">Nenhuma rede adicionada.</p>}</div><SectionEditor section={sections.find((s) => s.id === 'idiomas')!} entries={entriesFor('idiomas')} onAdd={() => patch({ entries: [...profile.entries, createEntry('idiomas')] })} onUpdate={updateEntry} onRemove={removeEntry} compact /></section>}

          {active.id === 'revisao' && <section className="space-y-5"><div className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">Revisão final</h2><p className="mt-1 text-sm text-slate-500">{issues.length ? `${issues.length} ponto(s) merecem atenção antes da geração.` : 'Tudo pronto para gerar.'}</p></div><Select value={profile.outputMode} onChange={(e) => patch({ outputMode: e.target.value as LattesProfile['outputMode'] })} className="sm:w-56"><option value="academico">Acadêmico premium</option><option value="edital">Versão para edital</option><option value="concurso">Versão para concurso</option><option value="internacional">Academic CV (English)</option></Select></div><div className="mt-5 space-y-2">{issues.length ? issues.map((issue) => <div key={issue.id} className={cn('flex gap-3 rounded-2xl border p-3', issue.severity === 'error' ? 'border-rose-200 bg-rose-50' : issue.severity === 'warning' ? 'border-amber-200 bg-amber-50' : 'border-sky-200 bg-sky-50')}><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" /><div><p className="text-sm font-bold">{issue.title}</p><p className="text-xs leading-5 opacity-75">{issue.detail}</p></div></div>) : <div className="rounded-2xl bg-emerald-50 p-5 text-emerald-800"><Check className="mb-2 h-6 w-6" /><b>Currículo consistente</b><p className="text-sm">Nenhum problema foi identificado.</p></div>}</div></div><AcademicPreview ref={previewRef} profile={profile} branded={brandDocuments} /></section>}

          <div className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-3"><Button variant="ghost" disabled={step === 0} onClick={() => patch({ currentStep: Math.max(0, step - 1) })}><ChevronLeft className="h-4 w-4" />Anterior</Button><span className="text-xs font-semibold text-slate-400">Etapa {step + 1} de {steps.length}</span>{step < steps.length - 1 ? <Button onClick={() => patch({ currentStep: step + 1 })}>Continuar<ChevronRight className="h-4 w-4" /></Button> : <Button onClick={exportPdf}><Download className="h-4 w-4" />Baixar PDF</Button>}</div>
        </main>

        <aside className="space-y-4 xl:sticky xl:top-5 xl:self-start"><section className="rounded-[24px] border border-slate-200 bg-white p-4 shadow-sm"><h3 className="flex items-center gap-2 text-sm font-bold"><FileSearch className="h-4 w-4 text-teal-700" />Importar produção</h3><p className="mt-1 text-xs leading-5 text-slate-500">Consulte DOI via Crossref ou vincule um ORCID. Dados importados sempre exigem revisão.</p><Input className="mt-3" value={importValue} onChange={(e) => setImportValue(e.target.value)} placeholder="DOI ou ORCID" /><Button className="mt-2 w-full" variant="outline" onClick={importAcademic} disabled={importing}>{importing ? <Loader2 className="h-4 w-4 animate-spin" /> : <BookOpen className="h-4 w-4" />}Consultar</Button></section><section className="rounded-[24px] border border-dashed border-slate-300 bg-slate-50 p-4"><input ref={fileRef} type="file" multiple accept=".pdf,.png,.jpg,.jpeg" className="hidden" onChange={handleUpload} /><button className="w-full text-center" onClick={() => fileRef.current?.click()}><span className="mx-auto grid h-10 w-10 place-items-center rounded-xl bg-white text-teal-700 shadow-sm">{uploading ? <Loader2 className="h-5 w-5 animate-spin" /> : <Upload className="h-5 w-5" />}</span><b className="mt-2 block text-sm">Diplomas, certificados e artigos</b><span className="mt-1 block text-xs leading-5 text-slate-500">PDF ou imagem · múltiplos arquivos</span></button></section><section className="rounded-[24px] bg-slate-950 p-4 text-white"><p className="text-xs font-bold uppercase tracking-widest text-teal-300">Transparência</p><p className="mt-2 text-xs leading-5 text-slate-300">Este módulo organiza dados compatíveis com o ecossistema acadêmico brasileiro, mas não possui integração oficial nem envia informações à Plataforma Lattes.</p></section>{error && <p className="rounded-2xl bg-rose-50 p-3 text-xs font-semibold text-rose-700">{error}</p>}</aside>
      </div>
    </div>
  </AuthGate>;
}

function SectionEditor({ section, entries, onAdd, onUpdate, onRemove, compact = false }: { section: typeof sections[number]; entries: AcademicEntry[]; onAdd: () => void; onUpdate: (id: string, changes: Partial<AcademicEntry>) => void; onRemove: (id: string) => void; compact?: boolean }) {
  return <section className={cn('rounded-[28px] border border-slate-200 bg-white shadow-sm', compact ? 'mt-6 p-0 shadow-none' : 'p-5 sm:p-6')}><div className="flex items-start justify-between gap-4"><div><h2 className="font-bold text-slate-950">{section.label}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{section.description}</p></div><Button size="sm" variant="outline" onClick={onAdd}><Plus className="h-4 w-4" />Adicionar</Button></div>{entries.length ? <div className="mt-4 space-y-3">{entries.map((entry) => <article key={entry.id} className="rounded-2xl border border-slate-200 bg-slate-50/60 p-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Título / atividade"><Input value={entry.title} onChange={(e) => onUpdate(entry.id, { title: e.target.value })} /></Field><Field label="Instituição / veículo"><Input value={entry.institution} onChange={(e) => onUpdate(entry.id, { institution: e.target.value })} /></Field><Field label="Início / ano"><Input value={entry.startYear} onChange={(e) => onUpdate(entry.id, { startYear: e.target.value })} placeholder="2024" /></Field><Field label="Fim / situação"><Input value={entry.endYear} onChange={(e) => onUpdate(entry.id, { endYear: e.target.value })} placeholder="Atual" /></Field>{section.id === 'bibliografica' && <><Field label="DOI / ISBN / ISSN"><Input value={entry.identifier || ''} onChange={(e) => onUpdate(entry.id, { identifier: e.target.value })} /></Field><Field label="Autores"><Input value={entry.authors || ''} onChange={(e) => onUpdate(entry.id, { authors: e.target.value })} /></Field></>}<div className="sm:col-span-2"><Field label="Descrição"><Textarea rows={3} value={entry.description} onChange={(e) => onUpdate(entry.id, { description: e.target.value })} /></Field></div></div><button onClick={() => onRemove(entry.id)} className="mt-3 flex items-center gap-1 text-xs font-semibold text-rose-600"><Trash2 className="h-3.5 w-3.5" />Remover registro</button></article>)}</div> : <button onClick={onAdd} className="mt-4 flex w-full flex-col items-center rounded-2xl border border-dashed border-slate-300 p-6 text-center hover:border-teal-400 hover:bg-teal-50/40"><Plus className="h-5 w-5 text-teal-700" /><b className="mt-2 text-sm text-slate-700">Adicionar primeiro registro</b><span className="mt-1 text-xs text-slate-400">Você também pode usar o assistente acima.</span></button>}</section>;
}

const AcademicPreview = forwardRef<HTMLDivElement, { profile: LattesProfile; branded?: boolean }>(({ profile, branded = true }, ref) => <div ref={ref} className="mx-auto min-h-[297mm] max-w-[210mm] bg-white p-[16mm] text-slate-900 shadow-xl"><DocumentExportShell branded={branded}><header className="border-b-4 border-teal-700 pb-5"><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-teal-700">Currículo acadêmico · {profile.outputMode}</p><h1 className="mt-3 text-3xl font-bold">{profile.general.fullName || 'Seu nome completo'}</h1><p className="mt-1 text-sm text-slate-500">{profile.general.citationName} {profile.general.orcid && `· ORCID ${profile.general.orcid}`}</p><p className="mt-4 text-sm leading-6">{profile.general.summary || 'Seu resumo acadêmico aparecerá aqui.'}</p></header><div className="mt-6 space-y-6">{sections.map((section) => { const rows = profile.entries.filter((e) => e.section === section.id && e.title); if (!rows.length) return null; return <section key={section.id}><h2 className="mb-3 text-xs font-bold uppercase tracking-[0.18em] text-teal-800">{section.label}</h2><div className="space-y-3">{rows.map((row) => <div key={row.id} className="border-l-2 border-slate-200 pl-3"><div className="flex justify-between gap-4"><b className="text-sm">{row.title}</b><span className="shrink-0 text-[11px] text-slate-500">{row.startYear}{row.endYear && ` — ${row.endYear}`}</span></div><p className="text-xs font-medium text-slate-600">{row.institution}</p>{row.authors && <p className="mt-1 text-xs">{row.authors}</p>}{row.description && <p className="mt-1 text-xs leading-5 text-slate-600">{row.description}</p>}{row.identifier && <p className="mt-1 text-[10px] text-teal-700">{row.identifier}</p>}</div>)}</div></section>; })}</div></DocumentExportShell></div>);
AcademicPreview.displayName = 'AcademicPreview';
