import type { AcademicEntry, LattesProfile, ValidationIssue } from './types';
export const LATTES_STORAGE_KEY = 'resolva-jato:lattes-inteligente:v1';
export const makeId = (prefix = 'item') => `${prefix}_${Math.random().toString(36).slice(2, 9)}`;
export function createLattesProfile(): LattesProfile { return { id: makeId('lattes'), title: 'Meu currículo acadêmico', updatedAt: new Date().toISOString(), currentStep: 0, general: { fullName: '', citationName: '', nationality: 'Brasileira', city: '', email: '', orcid: '', summary: '' }, entries: [], keywords: [], academicNetworks: [], indicators: { articles: '', citations: '', hIndex: '', i10: '' }, outputMode: 'academico' }; }
export function createEntry(section: AcademicEntry['section'], partial: Partial<AcademicEntry> = {}): AcademicEntry { return { id: makeId(section), section, title: '', institution: '', startYear: '', endYear: '', description: '', ...partial }; }
export function validateProfile(profile: LattesProfile): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  if (!profile.general.fullName.trim()) issues.push({ id: 'nome', severity: 'error', title: 'Nome completo ausente', detail: 'Informe o nome usado nos documentos acadêmicos.', section: 'geral' });
  if (!profile.general.citationName.trim()) issues.push({ id: 'citacao', severity: 'warning', title: 'Nome em citações ausente', detail: 'Ajuda a reconciliar autoria em publicações.', section: 'geral' });
  if (profile.general.orcid && !/^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$/.test(profile.general.orcid)) issues.push({ id: 'orcid', severity: 'error', title: 'ORCID inválido', detail: 'Use o formato 0000-0000-0000-0000.', section: 'geral' });
  for (const item of profile.entries) { if (!item.title.trim()) issues.push({ id: `${item.id}-titulo`, severity: 'error', title: 'Registro sem título', detail: 'Todo registro acadêmico precisa de identificação.', section: item.section }); if (item.startYear && item.endYear && Number(item.startYear) > Number(item.endYear)) issues.push({ id: `${item.id}-datas`, severity: 'error', title: 'Período inconsistente', detail: `${item.title || 'Registro'} termina antes de começar.`, section: item.section }); }
  const seen = new Set<string>(); profile.entries.forEach((item) => { const key = `${item.section}:${item.title}:${item.startYear}`.toLowerCase(); if (item.title && seen.has(key)) issues.push({ id: `${item.id}-dup`, severity: 'warning', title: 'Possível duplicidade', detail: `“${item.title}” aparece mais de uma vez.`, section: item.section }); seen.add(key); });
  if (!profile.entries.some((item) => item.section === 'formacao')) issues.push({ id: 'formacao-vazia', severity: 'info', title: 'Formação ainda vazia', detail: 'Adicione sua principal titulação.', section: 'formacao' }); return issues;
}
export function completion(profile: LattesProfile) { const checks = [profile.general.fullName, profile.general.citationName, profile.general.summary, profile.general.orcid, profile.entries.some((e) => e.section === 'formacao'), profile.entries.some((e) => e.section === 'atuacao'), profile.entries.some((e) => e.section === 'bibliografica'), profile.keywords.length > 0]; return Math.round((checks.filter(Boolean).length / checks.length) * 100); }
